// 2019/2_concept/Client/src/pages/Auth/Register/index.vue
<template>
    <div>
        <b-row align-h="center">
            <b-col cols="6">
                <b-form-group
                        label="Register"
                        label-for="input-1"
                >
                    <b-form-input v-model="form.fname" placeholder="First Name" class="mt-3 mb-3"></b-form-input>
                    <b-form-input v-model="form.lname" placeholder="Last Name" class="mb-3"></b-form-input>
                    <b-form-input v-model="form.email" placeholder="Email" class="mb-3"></b-form-input>
                    <b-form-input v-model="form.phone" placeholder="Phone" class="mb-3" type="tel"></b-form-input>
                    <b-form-input v-model="form.pass" placeholder="Password" type="password"></b-form-input>
                </b-form-group>
            </b-col>
        </b-row>

        <b-row align-h="center" class="mt-5">
            <b-col cols="6">
                <b-form-group
                        label="Address"
                        label-for="input-1"
                >
                    <b-form-input v-model="form.address1" placeholder="Address 1" class="mt-3 mb-3"></b-form-input>
                    <b-form-input v-model="form.address2" placeholder="Address 2" class="mb-3"></b-form-input>
                    <b-form-input v-model="form.city" placeholder="City" class="mb-3"></b-form-input>
                    <b-button size="md" block variant="outline-secondary" class="float-right mt-3" @click="register(form, formAddress)">
                        Submit
                    </b-button>
                </b-form-group>
            </b-col>
        </b-row>

    </div>
</template>

<script>
    export default {
        data() {
            return {
                form: {
                    fname: null,
                    lname: null,
                    email: null,
                    phone: null,
                    password: null,
                    address1: null,
                    address2: null,
                    city: null
                }
            }
        },
        methods: {
            register(data) {
                this.$store.dispatch('auth/register', data)
            }
        }
    }
</script>

// 2019/2_concept/Admin/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {FormControl, FormGroup} from "@angular/forms";
import {AuthService} from "../../service/auth.service";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.sass']
})
export class RegisterComponent implements OnInit {
  registerForm = new FormGroup({
    fname: new FormControl(''),
    lname: new FormControl(''),
    email: new FormControl(''),
    phone: new FormControl(''),
    pass: new FormControl('')
  })

  constructor(
    private authService: AuthService
  ) { }

  register() {
    console.log('Register: ', this.registerForm.value)
    this.authService.register(this.registerForm.value).subscribe((result) => {
      console.log('REGISTER RESULT: ', result)
    })
  }

  ngOnInit() {
  }

}

<h4>Register</h4>

<div class="row justify-content-md-center">
  <div class="col col-6 mt-5">
    <form [formGroup]="registerForm" (ngSubmit)="register()">

      <div class="form-group">
        <label>First name</label>
        <input type="text" class="form-control" formControlName="fname">
      </div>
      <div class="form-group">
        <label>Last name</label>
        <input type="text" class="form-control" formControlName="lname">
      </div>
      <div class="form-group">
        <label>Email address</label>
        <input type="email" class="form-control" formControlName="email">
      </div>
      <div class="form-group">
        <label>Phone</label>
        <input type="phone" class="form-control" formControlName="phone">
      </div>
      <div class="form-group">
        <label>Password</label>
        <input type="password" class="form-control" formControlName="pass">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>

    </form>
  </div>
</div>
